version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    container_name: caremap-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  caremap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caremap-app
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "5173:5173"
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./caremap_logs:/app/caremap_logs

volumes:
  pgdata:
